apiVersion: v1
kind: Service
metadata:
  name: flights-service
spec:
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
      nodePort: 30777
  selector:
    app: flights
  type: NodePort

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  labels:
    app: postgresql
    tier: database
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql
    tier: database